//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomaton.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellularAutomaton.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширение файла в который осуществляется сохранение записи..
        /// </summary>
        internal static string CellularAutomatonRecorder__FileExtensionDescr {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__FileExtensionDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр имён файлов в диалоговом окне &quot;Сохранить как...&quot;..
        /// </summary>
        internal static string CellularAutomatonRecorder__FileFilterDescr {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__FileFilterDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла в который осуществляется сохранение записи..
        /// </summary>
        internal static string CellularAutomatonRecorder__FileNameDescr {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__FileNameDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на record.
        /// </summary>
        internal static string CellularAutomatonRecorder__SaveFileDialogRecordDefFileName {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__SaveFileDialogRecordDefFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bin.
        /// </summary>
        internal static string CellularAutomatonRecorder__SaveFileDialogRecordExt {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__SaveFileDialogRecordExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двоичные файлы (*.bin)|*.bin.
        /// </summary>
        internal static string CellularAutomatonRecorder__SaveFileDialogRecordFilter {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__SaveFileDialogRecordFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить запись как....
        /// </summary>
        internal static string CellularAutomatonRecorder__SaveFileDialogRecordTitle {
            get {
                return ResourceManager.GetString("CellularAutomatonRecorder__SaveFileDialogRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнена попытка перехода к кадру номер которого больше, чем кадров в текущей записи..
        /// </summary>
        internal static string Ex__Выполнена_попытка_перехода_к_кадру_номер_которого_больше__чем_кадров_в_текущей_записи_ {
            get {
                return ResourceManager.GetString("Ex__Выполнена_попытка_перехода_к_кадру_номер_которого_больше__чем_кадров_в_текуще" +
                        "й_записи_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнена попытка перехода к кадру с отрицательным индексом..
        /// </summary>
        internal static string Ex__Выполнена_попытка_перехода_к_кадру_с_отрицательным_индексом_ {
            get {
                return ResourceManager.GetString("Ex__Выполнена_попытка_перехода_к_кадру_с_отрицательным_индексом_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &apos;{0}&apos; должно лежать в диапазоне от &apos;{1}&apos; до &apos;{2}&apos;..
        /// </summary>
        internal static string Ex__Значение___0___должно_лежать_в_диапазоне_от___1___до___2___ {
            get {
                return ResourceManager.GetString("Ex__Значение___0___должно_лежать_в_диапазоне_от___1___до___2___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &apos;{0}&apos; не должно быть меньше &apos;{1}&apos;..
        /// </summary>
        internal static string Ex__Значение___0___не_должно_быть_меньше___1___ {
            get {
                return ResourceManager.GetString("Ex__Значение___0___не_должно_быть_меньше___1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение высоты или ширины размера меньше или равно нулю..
        /// </summary>
        internal static string Ex__Значение_высоты_или_ширины_размера_меньше_или_равно_нулю_ {
            get {
                return ResourceManager.GetString("Ex__Значение_высоты_или_ширины_размера_меньше_или_равно_нулю_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число кадров в минуту не может быть равной нулю величиной..
        /// </summary>
        internal static string Ex__Число_кадров_в_минуту_не_может_быть_равной_нулю_величиной_ {
            get {
                return ResourceManager.GetString("Ex__Число_кадров_в_минуту_не_может_быть_равной_нулю_величиной_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число на которое перемещается ползунок по шкале поиска при щелчке мыши по элементу управления или нажатию клавиш PAGE UP, PAGE DOWN..
        /// </summary>
        internal static string PlayerController__FinderLargeChangeDescr {
            get {
                return ResourceManager.GetString("PlayerController__FinderLargeChangeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число на которое перемещается ползунок по шкале поиска при прокрутке колёсика мыши или нажатия клавиш LEFT, RIGHT, UP, DOWN..
        /// </summary>
        internal static string PlayerController__FinderSmallChangeDescr {
            get {
                return ResourceManager.GetString("PlayerController__FinderSmallChangeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал между отметками на шкале поиска..
        /// </summary>
        internal static string PlayerController__FinderTickFrequencyDescr {
            get {
                return ResourceManager.GetString("PlayerController__FinderTickFrequencyDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}/{1}.
        /// </summary>
        internal static string PlayerController__SetToolTip__Finder {
            get {
                return ResourceManager.GetString("PlayerController__SetToolTip__Finder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приостановить воспроизведение записи..
        /// </summary>
        internal static string PlayerController__SetToolTip__Pause {
            get {
                return ResourceManager.GetString("PlayerController__SetToolTip__Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать воспроизведение записи..
        /// </summary>
        internal static string PlayerController__SetToolTip__Play {
            get {
                return ResourceManager.GetString("PlayerController__SetToolTip__Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Останавливает воспроизведение записи..
        /// </summary>
        internal static string PlayerController__SetToolTip__Stop {
            get {
                return ResourceManager.GetString("PlayerController__SetToolTip__Stop", resourceCulture);
            }
        }
    }
}
