//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomaton.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellularAutomaton.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string DencityMaxDefValue {
            get {
                return ResourceManager.GetString("DencityMaxDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string DencityMinDefValue {
            get {
                return ResourceManager.GetString("DencityMinDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string DencityValueDefValue {
            get {
                return ResourceManager.GetString("DencityValueDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнена попытка перехода к кадру номер которого больше, чем кадров в текущей записи..
        /// </summary>
        internal static string Ex__Выполнена_попытка_перехода_к_кадру_номер_которого_больше__чем_кадров_в_текущей_записи_ {
            get {
                return ResourceManager.GetString("Ex__Выполнена_попытка_перехода_к_кадру_номер_которого_больше__чем_кадров_в_текуще" +
                        "й_записи_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнена попытка перехода к кадру с отрицательным индексом..
        /// </summary>
        internal static string Ex__Выполнена_попытка_перехода_к_кадру_с_отрицательным_индексом_ {
            get {
                return ResourceManager.GetString("Ex__Выполнена_попытка_перехода_к_кадру_с_отрицательным_индексом_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &apos;{0}&apos; должно лежать в диапазоне от &apos;{1}&apos; до &apos;{2}&apos;..
        /// </summary>
        internal static string Ex__Значение___0___должно_лежать_в_диапазоне_от___1___до___2___ {
            get {
                return ResourceManager.GetString("Ex__Значение___0___должно_лежать_в_диапазоне_от___1___до___2___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &apos;{0}&apos; не должно быть меньше &apos;{1}&apos;..
        /// </summary>
        internal static string Ex__Значение___0___не_должно_быть_меньше___1___ {
            get {
                return ResourceManager.GetString("Ex__Значение___0___не_должно_быть_меньше___1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение высоты или ширины размера меньше или равно нулю..
        /// </summary>
        internal static string Ex__Значение_высоты_или_ширины_размера_меньше_или_равно_нулю_ {
            get {
                return ResourceManager.GetString("Ex__Значение_высоты_или_ширины_размера_меньше_или_равно_нулю_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число кадров в минуту не может быть равной нулю величиной..
        /// </summary>
        internal static string Ex__Число_кадров_в_минуту_не_может_быть_равной_нулю_величиной_ {
            get {
                return ResourceManager.GetString("Ex__Число_кадров_в_минуту_не_может_быть_равной_нулю_величиной_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}/{1}.
        /// </summary>
        internal static string PlayerController__SetToolTipFinder {
            get {
                return ResourceManager.GetString("PlayerController__SetToolTipFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на record.
        /// </summary>
        internal static string SaveFileDialogRecordDefFileName {
            get {
                return ResourceManager.GetString("SaveFileDialogRecordDefFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bin.
        /// </summary>
        internal static string SaveFileDialogRecordExt {
            get {
                return ResourceManager.GetString("SaveFileDialogRecordExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двоичные файлы (*.bin)|*.bin.
        /// </summary>
        internal static string SaveFileDialogRecordFilter {
            get {
                return ResourceManager.GetString("SaveFileDialogRecordFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить запись как....
        /// </summary>
        internal static string SaveFileDialogRecordTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500.
        /// </summary>
        internal static string SizeFieldHeightMaxDefValue {
            get {
                return ResourceManager.GetString("SizeFieldHeightMaxDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string SizeFieldHeightMinDefValue {
            get {
                return ResourceManager.GetString("SizeFieldHeightMinDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string SizeFieldHeightValueDefValue {
            get {
                return ResourceManager.GetString("SizeFieldHeightValueDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500.
        /// </summary>
        internal static string SizeFieldWidthMaxDefValue {
            get {
                return ResourceManager.GetString("SizeFieldWidthMaxDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string SizeFieldWidthMinDefValue {
            get {
                return ResourceManager.GetString("SizeFieldWidthMinDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string SizeFieldWidthValueDefValue {
            get {
                return ResourceManager.GetString("SizeFieldWidthValueDefValue", resourceCulture);
            }
        }
    }
}
