//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomaton.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellularAutomaton.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнена попытка перехода к кадру номер которого больше, чем кадров в текущей записи..
        /// </summary>
        internal static string Ex__Выполнена_попытка_перехода_к_кадру_номер_которого_больше__чем_кадров_в_текущей_записи_ {
            get {
                return ResourceManager.GetString("Ex__Выполнена_попытка_перехода_к_кадру_номер_которого_больше__чем_кадров_в_текуще" +
                        "й_записи_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнена попытка перехода к кадру с отрицательным индексом..
        /// </summary>
        internal static string Ex__Выполнена_попытка_перехода_к_кадру_с_отрицательным_индексом_ {
            get {
                return ResourceManager.GetString("Ex__Выполнена_попытка_перехода_к_кадру_с_отрицательным_индексом_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота поля {0} меньше нуля..
        /// </summary>
        internal static string Ex__Высота_поля__0__меньше_нуля_ {
            get {
                return ResourceManager.GetString("Ex__Высота_поля__0__меньше_нуля_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение высоты или ширины размера меньше или равно нулю..
        /// </summary>
        internal static string Ex__Значение_высоты_или_ширины_размера_меньше_или_равно_нулю_ {
            get {
                return ResourceManager.GetString("Ex__Значение_высоты_или_ширины_размера_меньше_или_равно_нулю_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла не задано, пустое или состоит из одних пробелов..
        /// </summary>
        internal static string Ex__Имя_файла_не_задано__пустое_или_состоит_из_одних_пробелов_ {
            get {
                return ResourceManager.GetString("Ex__Имя_файла_не_задано__пустое_или_состоит_из_одних_пробелов_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение параметра {0}..
        /// </summary>
        internal static string Ex__Недопустимое_значение_параметра__0__ {
            get {
                return ResourceManager.GetString("Ex__Недопустимое_значение_параметра__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число кадров в минуту не может быть равной нулю величиной..
        /// </summary>
        internal static string Ex__Число_кадров_в_минуту_не_может_быть_равной_нулю_величиной_ {
            get {
                return ResourceManager.GetString("Ex__Число_кадров_в_минуту_не_может_быть_равной_нулю_величиной_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина поля {0} меньше нуля..
        /// </summary>
        internal static string Ex__Ширина_поля__0__меньше_нуля_ {
            get {
                return ResourceManager.GetString("Ex__Ширина_поля__0__меньше_нуля_", resourceCulture);
            }
        }
    }
}
