//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellularAutomaton.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellularAutomaton.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реакция Белоусова-Жаботинского.
        /// </summary>
        internal static string BelousovZhabotinskyReaction_Name {
            get {
                return ResourceManager.GetString("BelousovZhabotinskyReaction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Величина плотности распределения живых клеток на поле должна лежать в интервале [0; 100]..
        /// </summary>
        internal static string Ex__DensityOutOfRange {
            get {
                return ResourceManager.GetString("Ex__DensityOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не совпадают размеры текущего и заданного полей..
        /// </summary>
        internal static string Ex__Not_match_sizes_fields {
            get {
                return ResourceManager.GetString("Ex__Not_match_sizes_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество элементов в записи превышает доступное место, начиная с индекса {0} до конца массива назначения {1}.
        /// </summary>
        internal static string Ex__Record_CopyTo_ArgumentException {
            get {
                return ResourceManager.GetString("Ex__Record.CopyTo_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество состояний клетки клеточного автомата должно лежать в интервале [{0}; {1}]..
        /// </summary>
        internal static string Ex__StatesCountOutOfRange {
            get {
                return ResourceManager.GetString("Ex__StatesCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота поля {0} меньше нуля..
        /// </summary>
        internal static string Ex__Высота_поля__0__меньше_нуля_ {
            get {
                return ResourceManager.GetString("Ex__Высота_поля__0__меньше_нуля_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение параметра {0} меньше {1}..
        /// </summary>
        internal static string Ex__Значение_параметра__0__меньше__1__ {
            get {
                return ResourceManager.GetString("Ex__Значение_параметра__0__меньше__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла не задано, пустое или состоит из одних пробелов..
        /// </summary>
        internal static string Ex__Имя_файла_не_задано__пустое_или_состоит_из_одних_пробелов_ {
            get {
                return ResourceManager.GetString("Ex__Имя_файла_не_задано__пустое_или_состоит_из_одних_пробелов_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение параметра {0}..
        /// </summary>
        internal static string Ex__Недопустимое_значение_параметра__0__ {
            get {
                return ResourceManager.GetString("Ex__Недопустимое_значение_параметра__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина поля {0} меньше нуля..
        /// </summary>
        internal static string Ex__Ширина_поля__0__меньше_нуля_ {
            get {
                return ResourceManager.GetString("Ex__Ширина_поля__0__меньше_нуля_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жизнь.
        /// </summary>
        internal static string Rule_Life_Name {
            get {
                return ResourceManager.GetString("Rule_Life_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Циклический автомат Мура.
        /// </summary>
        internal static string Rule_MooreCyclic_Name {
            get {
                return ResourceManager.GetString("Rule_MooreCyclic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автомат Мура.
        /// </summary>
        internal static string Rule_MooreSimple_Name {
            get {
                return ResourceManager.GetString("Rule_MooreSimple_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Циклический автомат Неймана.
        /// </summary>
        internal static string Rule_NeimanCyclic_Name {
            get {
                return ResourceManager.GetString("Rule_NeimanCyclic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автомат Неймана.
        /// </summary>
        internal static string Rule_NeimanSimple_Name {
            get {
                return ResourceManager.GetString("Rule_NeimanSimple_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одномерный автома.
        /// </summary>
        internal static string Rule_OneDimentionalCyclic_Name {
            get {
                return ResourceManager.GetString("Rule_OneDimentionalCyclic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поверхность Венеры.
        /// </summary>
        internal static string Rule_VenusSurface_Name {
            get {
                return ResourceManager.GetString("Rule_VenusSurface_Name", resourceCulture);
            }
        }
    }
}
